REGISTRY_SERVER ?= quay.io
REGISTRY_NAMESPACE ?= luban-ci
IMAGE_NAME ?= dagster-gateway
PLATFORM ?= linux/amd64
LUBAN_CI_ROOT ?= ../luban-ci
LUBAN_GATEWAY_CONFIG ?= $(LUBAN_CI_ROOT)/manifests/config/luban-dagster-gateway-config.yaml
